INSERT INTO Owner (
  Id,
  Name,
  Age,
  Dog_Name,
  Vet_Name)
  VALUES 
  (1, 'Aaron', 21, 'Matt', 'Leona'),
  (2, 'Brad', 32, 'Phil', 'Leona'),
  (3, 'Charity', 45, 'Fido', 'Michael'),
  (4, 'Deanna', 16, 'Brownie', 'James'),
  (5, 'Earl', 63, 'Ruff', 'Paul'),
  (6, 'Fani', 55, 'Midnight', 'Debbie'),
  (7, 'Gary', 25, 'Lassie', 'Marc'),
  (8, 'Heather', 25, 'Toto', 'Maria'),
  (9, 'Ivan', 17, 'Coco', 'Maria'),
  (10, 'Jesus', 65, 'Toy', 'Kumail'),
  (11, 'Kevin', 22, 'Charles', 'Dean'),
  (12, 'Lorraine', 47, 'Skippy', 'Imani'),
  (13, 'Michela', 18, 'Walley', 'Fredricka'),
  (14, 'Nikki', 62, 'Fred', 'Deb'),
  (15, 'Omar', 65, 'Piggy', 'Kumail'),
  (16, 'Paula', 73, 'Fox', 'Kara'),
  (17, 'Quincy', 55, 'True', 'Duane'),
  (18, 'Riley', 15, 'Mimi', 'Richard'),
  (19, 'Soo', 32, 'Trent', 'Scooter'),
  (20, 'Toby', 29, 'Any', 'Rachael'),
  (21, 'Unique', 23, 'Ivory', 'Debbie'),
  (22, 'Vera', 99, 'Ebony', 'Harold'),
  (23, 'Walker', 55, 'Pippy', 'Arlan'),
  (24, 'Xi', 33, 'Luke', 'Tasha'),
  (25, 'Zorro', 33, 'Zen', 'Kara');
  
